# Generated by Django 3.2.25 on 2024-12-15 15:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_cars', '0007_auto_20241215_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='features',
        ),
        migrations.RemoveField(
            model_name='test',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='test',
            name='my_field2',
        ),
        migrations.AddField(
            model_name='test',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')], default=(), max_length=26),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
